version: "2"

services:
  tellerbot-web:
    build:
      context: ./tellerbot-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - tellerbot-api
    networks:
      - tellerbot-net
  tellerbot-api:
    build:
      context: ./tellerbot-api
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    command: php artisan serve --host=0.0.0.0 --port=8181
    depends_on:
      - api-data
    networks:
      - tellerbot-net
  api-data:
    image: mysql:5.7.29
    ports:
      - "3306:3306"
    networks:
      - tellerbot-net
    volumes:
      - ./api-data/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sample
      - MYSQL_DATABASE=api-data
networks: 
  tellerbot-net:
    driver: bridge
